// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ujbvvjnkpfccstysvfji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqYnZ2am5rcGZjY3N0eXN2ZmppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyODc3MTIsImV4cCI6MjA1ODg2MzcxMn0.ki7LluK73QXXpxrwuyD0ygej7OIPRXX2xqH5MzxiVMs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);